version: 2

models:
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: stg_attendee
    columns:
      - name: event_id
        tests:
          - not_null
